# Generated by Django 5.1.7 on 2025-05-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0001_initial'),
    ]

    operations = [
    ]
