# Generated by Django 5.1.7 on 2025-05-26 19:26

import core.datetime_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0003_customer_added_by_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=core.datetime_utils.get_current_datetime),
        ),
    ]
