# Generated by Django 5.1.7 on 2025-05-23 16:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=20)),
                ('normal_balance', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('auto_calculate', models.BooleanField(default=False, help_text='Automatically calculated from system data')),
                ('manual_balance', models.DecimalField(decimal_places=2, default=0, help_text='Manual balance for non-auto accounts', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='journalentryline',
            name='account',
        ),
        migrations.RemoveField(
            model_name='trialbalanceline',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journalentryline',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='trialbalanceline',
            name='trial_balance',
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date', '-entry_number'], 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entry_number',
            field=models.CharField(default='AUTO', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the referenced object', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(blank=True, help_text='Type: sales_order, production, payroll, utilities, etc.', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('OWNER_INVESTMENT', "Owner's Investment"), ('OWNER_WITHDRAWAL', "Owner's Withdrawal"), ('EQUIPMENT_PURCHASE', 'Equipment Purchase'), ('LOAN_RECEIVED', 'Loan Received'), ('LOAN_PAYMENT', 'Loan Payment'), ('OTHER_INCOME', 'Other Income'), ('OTHER_EXPENSE', 'Other Expense')], max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transaction_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer')], default='CASH', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_pay', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer')], default='CASH', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-payment_date'],
                'unique_together': {('employee', 'pay_period_start', 'pay_period_end')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.journalentry')),
            ],
            options={
                'ordering': ['journal_entry', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UtilityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('INTERNET', 'Internet'), ('RENT', 'Rent'), ('MAINTENANCE', 'Maintenance'), ('SUPPLIES', 'Office Supplies'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('billing_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer')], default='CASH', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.DeleteModel(
            name='ChartOfAccounts',
        ),
        migrations.DeleteModel(
            name='JournalEntryLine',
        ),
        migrations.DeleteModel(
            name='TrialBalance',
        ),
        migrations.DeleteModel(
            name='TrialBalanceLine',
        ),
    ]
