# Generated by Django 5.1.7 on 2025-05-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='base_unit',
            field=models.CharField(default='1kg', help_text='Base unit for this material (e.g., 1kg, 100g, 1L)', max_length=50),
        ),
    ]
