# Generated by Django 5.1.7 on 2025-05-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rawmaterial_base_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='base_unit',
        ),
    ]
