# Generated by Django 5.1.7 on 2025-05-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_rawmaterial_base_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='base_unit',
            field=models.CharField(default='g', help_text='Base unit for inventory (e.g., g, ml, pcs)', max_length=10),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unit_conversion_factor',
            field=models.DecimalField(decimal_places=2, default=1, help_text='How many base units in one stock-in unit (e.g., 1000 for 1kg if base unit is g)', max_digits=10),
        ),
    ]
