# Generated by Django 5.1.7 on 2025-05-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rawmaterial_base_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['-date_started', '-production_number'], 'verbose_name': 'Production', 'verbose_name_plural': 'Productions'},
        ),
        migrations.RemoveField(
            model_name='production',
            name='date',
        ),
        migrations.AddField(
            model_name='production',
            name='date_finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='wastage_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='production_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ProductionBatchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_products', to='inventory.production')),
            ],
        ),
    ]
