# Generated by Django 5.1.7 on 2025-05-23 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('inventory', '0005_alter_production_options_remove_production_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='batch_type',
            field=models.CharField(choices=[('single', 'Single Product'), ('mixed', 'Mixed Batch')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='production',
            name='material_sufficiency_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='production',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('checking_materials', 'Checking Materials'), ('materials_insufficient', 'Materials Insufficient'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='FinishedGoodsInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('expired', 'Expired'), ('consumed', 'Fully Consumed')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_inventory', to='inventory.product')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_goods', to='inventory.production')),
            ],
            options={
                'verbose_name': 'Finished Goods Inventory',
                'verbose_name_plural': 'Finished Goods Inventory',
                'ordering': ['expiry_date', 'production_date'],
            },
        ),
        migrations.CreateModel(
            name='UnusedMaterialReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('return_reason', models.CharField(default='Production cancelled', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.rawmaterialmovement')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unused_returns', to='inventory.production')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rawmaterial')),
            ],
            options={
                'verbose_name': 'Unused Material Return',
                'verbose_name_plural': 'Unused Material Returns',
            },
        ),
        migrations.CreateModel(
            name='MaterialSufficiencyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_sufficient', models.BooleanField()),
                ('unit', models.CharField(max_length=20)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sufficiency_checks', to='inventory.production')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rawmaterial')),
            ],
            options={
                'verbose_name': 'Material Sufficiency Check',
                'verbose_name_plural': 'Material Sufficiency Checks',
                'unique_together': {('production', 'raw_material')},
            },
        ),
    ]
