# Generated by Django 5.1.7 on 2025-05-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_production_batch_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='batch_type',
        ),
        migrations.AlterField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='production',
            name='unit',
            field=models.CharField(default='pcs', max_length=50),
        ),
        migrations.AlterField(
            model_name='production',
            name='wastage_notes',
            field=models.TextField(blank=True, help_text='Notes about material wastage during cancellation'),
        ),
    ]
