# Generated by Django 5.1.7 on 2025-05-23 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_batch_type_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialmovement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
