# Generated by Django 5.1.7 on 2025-05-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_rawmaterialmovement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='credit', max_length=10),
        ),
    ]
