# Generated by Django 5.1.7 on 2025-05-26 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_remove_journalentryline_account_and_more'),
        ('inventory', '0009_add_payment_method_to_stockin'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry'),
        ),
    ]
