# Generated by Django 5.1.7 on 2025-05-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stockin_journal_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='journal_entry',
        ),
    ]
