# Generated by Django 5.1.7 on 2025-05-26 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_stockin_journal_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialmovement',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
