# Generated by Django 5.1.7 on 2025-05-26 19:03

import core.datetime_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_fix_raw_material_movement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialmovement',
            name='date',
            field=models.DateField(default=core.datetime_utils.get_current_date),
        ),
    ]
